from keyboards.keyboard import kb_main,kb_orders,kb_cancel,kb_login,kb_admin_main,kb_admin_delete_orders,main_menu_kb,main_user_menu_kb
from keyboards.inline_keyboard import inline_order_roll_kb,inline_order_burger_kb,inline_order_pizza_kb,inline_delete_roll_kb_admin
from keyboards.inline_keyboard import inline_delete_burger_kb_admin ,inline_delete_pizza_kb_admin
from keyboards.inline_keyboard import inline_delete_order_burger_kb,inline_delete_order_roll_kb,inline_delete_order_pizza_kb
